### ISSUE TITLE
Inconsistent ipv6only option

### ISSUE THREAD

**Issue by Nibb31** [OpenMediaVault-Plugin-Developers/openmediavault-nginx#16]
The latest version of nginx defaults to ipv6only=on, which means that if you want your website to work in ipv4 and ipv6, then ipvonly=off is mandatory. There seems to be a bug in the nginx plugin where it fails to add this option on SSL listen lines.

For HTTP, the plugin properly generates 'listen [::]:80 ipv6only=off;'. For HTTPS, the plugin generates 'listen [::]:80 ssl;' without the 'ipv6only=off' option.

One solution would be for the plugin to explicitly add the ipv6only=off option to the listen statement in SSL. However, there seems to be another issue where nginx refuses to restart if you have the ipv6only option set more than once for each port. This complicates things for the plugin when you have multiple servers on the same port (differentiated by server_name), as it can only be present in the first listen statement. The easiest solution for the plugin is probably to drop the ipv6only option and to generate two listen lines for each server to cover IPv4 and IPv6:
HTTP:
listen 80;
listen [::]:80;

HTTPS:
listen 443 ssl;
listen [::]:443 ssl;

Optionally, you could add a setting to the plugin UI to specify whether to use IPv4, IPv6 or both.

**Comment by nohatssir** [comment]
It should actually work as it is now because it'll will set `ipv6only=off` on only one of the entries on a port, and none if it's the same as the port OMV is running on (but maybe the code is broken). Does the `ipv6only` option depend on being defined in the first or last server entry?

But if the two lines works separately without interfering I think that would be a more foolproof plan. Can you check if it breaks with other configurations which includes the `ipv6only` option?

**Comment by Nibb31** [comment]
The plugin doesn't add the `ipv6only=off` option for SSL, so that's a first bug.

The option can be anywhere, but only declared once for each port.

I think that the two lines option is more robust. The plugin already generates two 'listen' lines if you select Enable SSL without the Use SSL only option. Doubling this with a line for IPv4 and another forIPv6 works fine here.
